/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotionDebugRouteImport } from './routes/notion-debug'
import { Route as NotionHealthRouteImport } from './routes/notion-health'
import { Route as NotionSchemaRouteImport } from './routes/notion-schema'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as StudentsRouteImport } from './routes/students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotionDebugRoute = NotionDebugRouteImport.update({
  id: '/notion-debug',
  path: '/notion-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const NotionHealthRoute = NotionHealthRouteImport.update({
  id: '/notion-health',
  path: '/notion-health',
  getParentRoute: () => rootRouteImport,
} as any)
const NotionSchemaRoute = NotionSchemaRouteImport.update({
  id: '/notion-schema',
  path: '/notion-schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notion-debug': typeof NotionDebugRoute
  '/notion-health': typeof NotionHealthRoute
  '/notion-schema': typeof NotionSchemaRoute
  '/resources': typeof ResourcesRoute
  '/schedule': typeof ScheduleRoute
  '/students': typeof StudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notion-debug': typeof NotionDebugRoute
  '/notion-health': typeof NotionHealthRoute
  '/notion-schema': typeof NotionSchemaRoute
  '/resources': typeof ResourcesRoute
  '/schedule': typeof ScheduleRoute
  '/students': typeof StudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notion-debug': typeof NotionDebugRoute
  '/notion-health': typeof NotionHealthRoute
  '/notion-schema': typeof NotionSchemaRoute
  '/resources': typeof ResourcesRoute
  '/schedule': typeof ScheduleRoute
  '/students': typeof StudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notion-debug'
    | '/notion-health'
    | '/notion-schema'
    | '/resources'
    | '/schedule'
    | '/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notion-debug'
    | '/notion-health'
    | '/notion-schema'
    | '/resources'
    | '/schedule'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/notion-debug'
    | '/notion-health'
    | '/notion-schema'
    | '/resources'
    | '/schedule'
    | '/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotionDebugRoute: typeof NotionDebugRoute
  NotionHealthRoute: typeof NotionHealthRoute
  NotionSchemaRoute: typeof NotionSchemaRoute
  ResourcesRoute: typeof ResourcesRoute
  ScheduleRoute: typeof ScheduleRoute
  StudentsRoute: typeof StudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notion-debug': {
      id: '/notion-debug'
      path: '/notion-debug'
      fullPath: '/notion-debug'
      preLoaderRoute: typeof NotionDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notion-health': {
      id: '/notion-health'
      path: '/notion-health'
      fullPath: '/notion-health'
      preLoaderRoute: typeof NotionHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notion-schema': {
      id: '/notion-schema'
      path: '/notion-schema'
      fullPath: '/notion-schema'
      preLoaderRoute: typeof NotionSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotionDebugRoute: NotionDebugRoute,
  NotionHealthRoute: NotionHealthRoute,
  NotionSchemaRoute: NotionSchemaRoute,
  ResourcesRoute: ResourcesRoute,
  ScheduleRoute: ScheduleRoute,
  StudentsRoute: StudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
